name: Cypress Tests in Docker

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # ✅ Enables Docker Buildx

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version  # ✅ Verifies installation

      - name: Set up Docker permissions
        run: |
          sudo chmod +x docker/*.sh
          sudo chmod +x docker/setup/setup.sh

      - name: Build and start containers
        run: |
          cd docker
          ./build.sh
          ./start.sh
          echo "Waiting for containers to be ready..."
          sleep 30
          docker ps
          docker-compose ps

      - name: Debug containers
        run: |
          docker ps -a
          echo "Docker compose status:"
          docker-compose ps
          echo "PHP-FPM container logs:"
          docker logs booking-php-fpm || true
          echo "Network info:"
          docker network ls
          docker inspect booking-php-fpm || true

      - name: Debug php-fpm inside the container
        run: |
          echo "Checking if php-fpm is installed..."
          docker-compose exec booking-php-fpm which php-fpm || echo "php-fpm not found"
          docker-compose exec booking-php-fpm php-fpm -v || echo "php-fpm is not working"

      - name: Set file permissions inside the container
        run: |
          cd /home/runner/work/Solutech-SDET/Solutech-SDET
          docker-compose exec -T booking-php-fpm chown -R www-data:www-data ./public

      - name: Install dependencies inside the container
        run: |
          docker-compose exec booking-php-fpm composer install
          docker-compose exec booking-php-fpm npm install
          docker-compose exec booking-php-fpm npm run build

      - name: Configure environment and database
        run: |
          docker-compose exec booking-php-fpm cp .env.example .env
          docker-compose exec booking-php-fpm php artisan key:generate
          docker-compose exec booking-php-fpm php artisan migrate:fresh --seed

      - name: Wait for Laravel to be ready
        run: |
          echo "Waiting for Laravel to be ready..."
          sleep 10 # Adjust if necessary
          curl --retry 10 --retry-delay 5 --retry-connrefused -I http://localhost:8000 || exit 1

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: "docker-compose up -d"
          wait-on: "http://localhost:8000"
          browser: chrome
          env: MOCHAWESOME_REPORT_DIR=cypress/reports
          config-file: cypress.json

      - name: Generate Test Report
        if: always()
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/combined.json
          npx mochawesome-report-generator cypress/reports/combined.json --reportDir cypress/reports

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/reports

      - name: Stop containers
        if: always()
        run: |
          cd docker
          ./stop.sh
