name: Cypress Tests in Docker

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Cypress
      run: npm ci

    - name: Make scripts executable
      run: |
        chmod +x docker/*.sh
        chmod +x docker/setup/setup.sh

    - name: Setup Docker environment
      run: |
        cd docker
        ./build.sh
        ./start.sh
        ./config.sh

    - name: Wait for application to be ready
      run: |
        # Wait for the application to be fully up
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000)" != "200" ]]; do sleep 5; done' || false

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        headed: false
        config: baseUrl=http://localhost:8000

    - name: Collect Docker logs on failure
      if: failure()
      run: |
        docker-compose logs > docker-logs.txt

    - name: Upload Docker logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: docker-logs
        path: docker-logs.txt

    - name: Stop Docker containers
      if: always()
      run: |
        cd docker
        ./stop.sh
