name: Cypress Tests in Docker

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d
          echo "Waiting for containers to be ready..."
          sleep 30

      - name: Check container status
        run: |
          docker-compose ps
          docker logs booking-php-fpm

      - name: Wait for services to be ready
        run: |
          echo "Checking PHP-FPM container..."
          until docker exec booking-php-fpm php-fpm -v > /dev/null 2>&1; do
            echo "Waiting for PHP-FPM to be ready..."
            sleep 5
          done

      - name: Set file permissions inside the container
        run: docker exec booking-php-fpm chown -R www-data:www-data /application/public

      # - name: Install dependencies inside the container
      #   run: |
      #     docker exec booking-php-fpm composer install
      #     docker exec booking-php-fpm npm install
      #     docker exec booking-php-fpm npm run build

      - name: Install dependencies inside the container
        run: |
          # Switch to root user for npm install
          docker exec -u root booking-php-fpm npm config set unsafe-perm true
          docker exec -u root booking-php-fpm npm install --location=global npm@latest
          docker exec -u root booking-php-fpm npm cache clean --force
          docker exec -u root booking-php-fpm npm install
          docker exec -u root booking-php-fpm npm run build
          # Switch back to www-data for other operations
          docker exec booking-php-fpm chown -R www-data:www-data /application/node_modules

      - name: Configure environment and database
        run: |
          docker exec booking-php-fpm cp .env.example .env
          docker exec booking-php-fpm php artisan key:generate
          docker exec booking-php-fpm php artisan migrate:fresh --seed

      - name: Wait for Laravel to be ready
        run: |
          echo "Waiting for Laravel to be ready..."
          sleep 10
          curl --retry 10 --retry-delay 5 --retry-connrefused -I http://localhost:8000 || exit 1

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: "docker-compose up -d"
          wait-on: "http://localhost:8000"
          browser: chrome
          env: MOCHAWESOME_REPORT_DIR=cypress/reports
          config-file: cypress.json

      - name: Generate Test Report
        if: always()
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/combined.json
          npx mochawesome-report-generator cypress/reports/combined.json --reportDir cypress/reports

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/reports

      - name: Stop containers
        if: always()
        run: docker-compose down
