# .github/workflows/post-merge-tests.yml
name: Post-Merge Tests

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-suite:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci

      - name: Generate key
        run: php artisan key:generate

      - name: Configure Database
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: root
          DB_PASSWORD: password
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Build assets
        run: npm run build

      - name: Start Laravel Server
        run: php artisan serve &
        env:
          APP_ENV: testing
          APP_URL: http://127.0.0.1:8000

      - name: Run All Tests
        run: |
          npm run test:e2e
          npm run test:features

      - name: Deploy if Tests Pass
        if: success()
        run: |
          echo "All tests passed - ready for deployment"
          # Add your deployment commands here

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '❌ Post-merge tests failed',
              body: `Tests failed on branch ${process.env.GITHUB_REF}\n[View Details](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})`
            });
