name: Run E2E Tests with Docker

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Verify docker directory and files
        id: verify-docker
        run: |
          if [ ! -d "docker" ]; then
            echo "The 'docker' directory is missing."
            exit 1
          fi
          cd docker
          if [ ! -f "build.sh" ] || [ ! -f "start.sh" ] || [ ! -f "config.sh" ] || [ ! -f "stop.sh" ]; then
            echo "One or more required .sh files are missing in the 'docker' directory."
            exit 1
          fi

      - name: Fix file permissions
        run: |
          cd docker
          sudo chmod +x *.sh
          sudo chmod +x setup/setup.sh

      - name: Build and start Docker containers
        run: |
          cd docker
          ./build.sh
          ./start.sh
