name: Run E2E Tests with Docker

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Verify docker directory and files
        id: verify-docker
        run: |
          if [ ! -d "docker" ]; then
            echo "The 'docker' directory is missing."
            exit 1
          fi
          cd docker
          if [ ! -f "build.sh" ] || [ ! -f "start.sh" ] || [ ! -f "config.sh" ] || [ ! -f "stop.sh" ]; then
            echo "One or more required .sh files are missing in the 'docker' directory."
            exit 1
          fi

      - name: Fix file permissions
        run: |
          cd docker
          sudo chmod +x *.sh
          sudo chmod +x setup/setup.sh

      - name: Build and start Docker containers
        run: |
          cd docker
          ./build.sh
          ./start.sh

      - name: Configure application container and seed database
        run: |
          cd docker
          ./config.sh

      - name: Run Cypress tests
        run: |
          cd docker
          docker exec -it <container_name> npx cypress run  # Replace <container_name> with your container name

      - name: Run Cucumber tests
        run: |
          cd docker
          docker exec -it <container_name> npm run test:cucumber  # Replace <container_name> with your container name

      - name: Stop Docker containers
        if: always()
        run: |
          cd docker
          ./stop.sh

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            cypress/results/*.json
            e2e/results/*.json
